print()
print("╔══════════════════════════════════════════╗")
print("║   BadBackend 生存指南 — Demo              ║")
print("║   Swift 網路層生存指南 系列文章           ║")
print("╚══════════════════════════════════════════╝")
print()

Scene1_SafeBox.run()
print()
Scene2_SafeArray.run()
print()
Scene3_Navigation.run()
print()
Scene4_Fuse.run()

print()
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print("✅ 所有場景跑完，App 沒有崩潰。")
print("   Bad backend 不是你的錯，但穩定是你的責任。")
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
print()
